### ISSUE TITLE
check if current_person exists

### ISSUE THREAD

**Issue by lislis** [rubycorns/RailsGirlsApp#312]
I introduced a bug in the already merged 'remove person from group' link thing. I don't check if the current_person exists which causes a bug if you're not logged in at all.
Do we have a helper for that?
Anyway, I'll try and fix it tomorrow

**Comment by til** [comment]
You mean like `person_signed_in?`?

**Comment by lislis** [comment]
Is that a thing? I only found `logged_in?` in the people helper which only checks if the current_person is the person it gets as an argument. But I need to check if there is a current_person and if current_person has admin rights

**Comment by berlintam** [comment]
We use `person_signed_in?` here: https://github.com/rubycorns/RailsGirlsApp/blob/master/app/helpers/groups_helper.rb#L4

Maybe it comes from devise?

**Comment by lislis** [comment]
I fixed it with `person_signed_in?` which does come from devise. But I'd kind of like to have a `is_admin?` helper that combines that w/ `has_role? 'admin'` But we can refactor that :)

**Comment by til** [comment]
Nice idea to have a combined `admin?` helper, that would allow us to tidy up a lot of views.

Note that rubocop and its friends recommend against prefixing predicate methods with `is_`, so I'd call it just `admin?` (https://github.com/bbatsov/ruby-style-guide#naming)
