### ISSUE TITLE
No sloth on 403 page :-(

### ISSUE THREAD

**Issue by til** [rubycorns/RailsGirlsApp#316]
On the 403 page, e.g. when I go to http://rorganize.it/groups/3/edit , the gif is broken!!!

Here's the offending html:

```html
<img src="sloth403.gif" alt="cute sloth">
```

**Comment by til** [comment]
![no-sloth](https://cloud.githubusercontent.com/assets/11211/6236091/bcb3cf90-b6e7-11e4-8057-85bd3cccbae7.png)

**Comment by lislis** [comment]
fixed in 938b33eb57dc21a5cecdd9b5592f4e739c and now deployed

**Comment by til** [comment]
Yippie, the sloth is back! Owesome!

**Comment by lislis** [comment]
So omazing!

**Comment by berlintam** [comment]
thank god!!
